baseURL = "https://powwow78.github.io/"
languageCode = "en-us"
title = "파우와우의 블로그"
theme = "PaperMod"
buildDrafts = true

[pagination]
  pagerSize = 5

[params]
  # home-info mode
  [params.homeInfoParams]
    Title = "파우와우의 블로그"
    Content = "나의 로그"

  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/"

[menu]

  [[menu.main]]
    identifier = "categories"
    name = "categories"
    url = "/categories/"
    weight = 10

  [[menu.main]]
    identifier = "tags"
    name = "tags"
    url = "/tags/"
    weight = 20

[caches]
  [caches.images]
    dir = ":cacheDir/images"

